### ISSUE TITLE
How creat this button?

### ISSUE THREAD

**Issue by djmalin** [herveaurel/HomeAssistant#1]
Hello @herveaurel pleace show me your code , how create this button? [Picture](https://imgur.com/a/CncAzih)

**Comment by herveaurel** [comment]
Look at lovelace.yaml, ligne 3030.

**Comment by herveaurel** [comment]
> Hello @herveaurel pleace show me your code , how create this button? [Picture](https://imgur.com/a/CncAzih)

Look at lovelace.yaml, ligne 3030.
