### ISSUE TITLE
Contenu des input_boolean.sidecar_show et les scripts 

### ISSUE THREAD

**Issue by Sonic62** [herveaurel/HomeAssistant#11]
Hello

tu pourrais mettre ce que contient les fichiers 

input_boolean.sidecar_show_*****
et tes scripts et scenes 

Merci

**Comment by herveaurel** [comment]
Bonjour. 
Pour les input je pense avoir expliqué sur mon github déjà. 

Les scripts je verrai. 
Les scènes, je trouve cela inutile de les partager, simplement des jeux de lumières propres à chacun. 

Cordialement.

**Comment by GregTroar** [comment]
Pour les input_boolean comment tu actives ton mode vacances / activites / ete par exemple ?

**Comment by herveaurel** [comment]
> Ah ok tu actives a la main ! merci beaucoup

Certains modes sont automatiques. C'est au choix.
