### ISSUE TITLE
Mouvements

### ISSUE THREAD

**Issue by GregTroar** [herveaurel/HomeAssistant#12]
Bonjour a toi,

Tout d'abord franchement bravo pour ton dashboard il est magnifique.
Je me lance mais c'est dur dur tellement il y a d'informations :)

J'essaie de reproduire ta custom:button-card pour les mouvements.

Pourrais tu me confirmer stp ce qu'il y a dans ton groupe: binary_sensor.mouvements ?
J'essaie d'utiliser le capteur d'activite de Home assistant compagnon sur Android mais dans un groupe binary_sensor je ne peux pas les rajouter.

Comments fais tu ?

Merci

**Comment by herveaurel** [comment]
Bonjour, c'est le groupe, de tous les capteurs mouvements, créé via la console.

**Comment by GregTroar** [comment]
Ok merci j'avais mal compris je pensais que c'etait comme un device tracker du telephone mais ce sont de vrais detecteurs de mouvements !
Merci.
