### ISSUE TITLE
Calcul KMS 

### ISSUE THREAD

**Issue by Sonic62** [herveaurel/HomeAssistant#14]
Hello

pour calculé les kms , tu te sert de google , waze , autres ??

J'ai vue que dans tes captures , que tu as un doublon de tes apps installé !

Ensuite a tu encore des soucis de refresh 
Car comme tu peux le voir 
![Capture d’écran 2023-04-15 222241](https://user-images.githubusercontent.com/103725660/232251756-64484dbd-5139-420b-8719-c7bf0999c6ca.png)

ca remonte pas 
![Capture d’écran 2023-04-15 222604](https://user-images.githubusercontent.com/103725660/232251802-1cc8852f-3962-4969-b414-135b68119075.png)

**Comment by herveaurel** [comment]
@Sonic62 
J'utilise Waze pour les km. 
Non je n'ai aucun soucis de refresh, toutes les infos sont partout en meme temps. Attention a rectifier / adapter mon template pour les mise a jour de hacs, car la prise en compte est a partir de 2 MàJ dispo car j'avais un bug, que je n'ai plus, le template sera corrigé dans la prochaine MàJ. 
Merci pour le doublon, c'est corrigé.

**Comment by Sonic62** [comment]
Hello

bien vue pour le sensor, MAJ , j'avais oublié de le modifié

**Comment by herveaurel** [comment]
> Hello
> 
> bien vue pour le sensor, MAJ , j'avais oublié de le modifié

✌🏻
