### ISSUE TITLE
Enregistrements

### ISSUE THREAD

**Issue by cob94440** [herveaurel/HomeAssistant#17]
Bonjour,

Je trouve ton boulot énorme et très inspirant.
Sur la page sécurité, je ne comprends pas la partie enregistrements. 
Ce serait intéressant également que tu mettes des infos sur le matos utilisé ainsi plus facile à adapter.
Merci d'avance

**Comment by herveaurel** [comment]
La partie enregistrement est liée avec la doc sur Doods2. (Reconnaissance de personne sur des captures photos de caméras)

**Comment by cob94440** [comment]
Merci pour ton aide c'est top.

Je serai intéressé aussi par ta présentation de pronote.

Plutot que publier toujours l'ensemble de ton dashboard tu pourrais juste faire par nouveauté. 

un peu comme sur ce github [](https://github.com/berkansezer77/home-assistant)

Pas mal d'idées intéressantes sur son repo
