### ISSUE TITLE
Big thanks for sharing your dashboard

### ISSUE THREAD

**Issue by Bidalos** [herveaurel/HomeAssistant#18]
Hey,
Could you please add your config , and other settings like group, media_player and scripts ?
I'm new and a little bit lost with what is media_player.musique is for for example, or what is inside group.machines, or what is scene.turn_on, etc etc .
Big thanks!

**Comment by herveaurel** [comment]
Hello and thank you

For me, there is no point in sharing everything.
And it also requires a lot of work to have clean and up-to-date files for sharing.

media_player.musique : 
This is a group that brings together all my music media_player entities. (13Alexa)

group.machines:
In this group, there is my washing machine, the drying machine, and my dishwasher.

scene.turn_on:
This is a Home Assistant service.
