### ISSUE TITLE
Style problem [card_mod]

### ISSUE THREAD

**Issue by Bidalos** [herveaurel/HomeAssistant#20]
Bonjour,
Merci pour le partage.
Je n'arrive pas à comprendre pourquoi le style visuel n'est pas conforme à tes captures.
Ici y a même pas de padding à gauche sur Programme et les icônes en dessous .![Screenshot_20240221-151559.png](https://github.com/herveaurel/HomeAssistant/assets/1233485/fc7ba4fb-5bc5-4317-aecd-6943fb4a0ac3)

Merci!

**Comment by herveaurel** [comment]
Bonjour. 
Je ne peux pas deviner. 
Un soucis avec card mod peut-être.

**Comment by Bidalos** [comment]
J'ai du modifier le sensor card template, en modifiant le padding left 0 à 10px.
Merci

**Comment by herveaurel** [comment]
> J'ai du modifier le sensor card template, en modifiant le padding left 0 à 10px.
> Merci

C'est géré par card mod normalement. 🙂
