### ISSUE TITLE
Missing sensor

### ISSUE THREAD

**Issue by cob94440** [herveaurel/HomeAssistant#21]
Bonjour, Sur ta carte activité il manque un sensor : sensor.calendrier_des_poubelles
Je ne le retrouve pas dans les templates.
Et du coup comme toi aussi tu as spook il génère une erreur.
Merci d'avance de ton aide

**Comment by herveaurel** [comment]
Bonjour, c'est un vieux sensor. 
Supprime toute cette ligne "entity". Ca devrait fonctionner sans.
