### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by KPI33** [herveaurel/HomeAssistant#22]
Salut,

J'aime beaucoup ton dashboard !
Je voulais copié puis ajuster mais j'ai un peu de mal à comprendre où il faut que je réalise les différentes copies.
Tu saurais m'aiguiller un peu pour que je puisse m'inspirer de ton travail ?
Merci !

**Comment by herveaurel** [comment]
Bonjour, 

Je ne fais pas d'aide personnalisée à ce point je n'ai pas le temps. 
Cette configuration demande un minimum de connaissance. 
Pour info, je n'ai plus autant de temps pour HA, alors j'abandonne mes créations, et je suis passé a [Bubble Card](https://github.com/Clooos/Bubble-Card), magnifique et surpuissant travail de mon ami Quentin. 😉

<img width="1390" alt="image" src="https://github.com/user-attachments/assets/acb0f1d4-09fb-4219-a4cd-7d6655ec241f">

**Comment by JefNewTech** [comment]
Magnifique, je suppose que tu n'a plus le temps de nettoyer ton code pour le partager.

**Comment by herveaurel** [comment]
Je le ferai peut-être pour faire de la pub à Quentin !

**Comment by werkey** [comment]
Salut, 
Merci pour ton travail, j'étais aussi parti sur ta solution précédente initialement (toujours en cours de mise en place) mais j'ai l'impression que la nouvelle solution avec les bubble card à l'air beaucoup plus rapide à mettre en place. Serait-il possible que tu nous partage ton yaml stp ?
Avec quoi as tu réalisé tes plans ?
Merci par avance !

**Comment by herveaurel** [comment]
Chaque chose en son temps. 
J'entame la phase "corrections des bugs". 
Ensuite quelques rares donateurs auront les codes en avant première pour tester. 
Et plus tard, et surtout quand j'aurais le temps, il y aura la mise à jour de mon Github. 
Quelques screens récents ici: [forum](https://forum.hacf.fr/t/carte-bubble-card-des-pop-up-et-une-collection-de-cartes-minimalistes/28028/148)

**Comment by JefNewTech** [comment]
Ah un petit don pour le code en bêta ☺️

**Comment by herveaurel** [comment]
> Ah un petit don pour le code en bêta ☺️

Non ça ne sert à rien. 
J'ai suffisamment de personnes qui testeront et je ne tiens pas à en avoir plus. 
Alors garde ton argent 🙂

**Comment by JefNewTech** [comment]
Je te rassure si je le fait c'est de bon cœur. Juste en remerciement à ton partage. Je n'attend rien en retour. ☺️
