### ISSUE TITLE
Template et Sensor Energie

### ISSUE THREAD

**Issue by fufurax** [herveaurel/HomeAssistant#23]
Bonjour,
Félicitations pour ton tableau de bord.
J'essais de m'inspirer de ton projet pour faire le mien sur la partie Energie mais je pense qu'il manque des fichiers. Par example, je ne trouve pas les templates👍 
```
  template:
    - ball_card
    - electricity_state
```
mais aussi le sensor avec qui calcul avec Abo : sensor.electricite_cout_jour_avec_abo

merci pour ton aide

**Comment by herveaurel** [comment]
Tout est sur le github. 
Soit dans lovelace pour les templates button card, soit dans les fichiers yaml pour les sensors.

**Comment by fufurax** [comment]
Je confirme qu'ils n'y sont pas

**Comment by herveaurel** [comment]
> Je confirme qu'ils n'y sont pas

La seule chose que tu peux confirmer est que tu n'as pas trouvé mais sûrement pas qu'ils n'y sont pas.
