### ISSUE TITLE
content_card_linky

### ISSUE THREAD

**Issue by FarleighRed** [herveaurel/HomeAssistant#25]
Is it possible to get the code for the Custom:content-card_linky please

Loving this dashboard and learning so much at the same time.

**Comment by herveaurel** [comment]
Custom:content-card_linky : It’s a hacs card

**Comment by FarleighRed** [comment]
I thought it might be, but was struggling to find it for some reason.Do you by any chance have a link?Thanks for sharing this dashboard, I see you are also a keen follower of bubble card which I also useRegardsJulianSent from my iPhoneOn 18 Oct 2024, at 15:39, MadGeek ***@***.***> wrote:﻿
Custom:content-card_linky : It’s a hacs card

**Comment by FarleighRed** [comment]
Found it, thanks
