### ISSUE TITLE
Précisions sur l'installation

### ISSUE THREAD

**Issue by sorcer1** [herveaurel/HomeAssistant#26]
Bonjour
,
Tout d'abord un grand bravo pour ce dashboard !
J'ai installé tous les addons et je cherche maintenant à savoir ce que je dois faire de ces 3 fichiers :
lovelace.yaml
sensor.yaml
template.yaml

Désolé si ma question peut paraître anodine.

Merci.

**Comment by herveaurel** [comment]
Read the chapter: installation
