### ISSUE TITLE
Input

### ISSUE THREAD

**Issue by cob94440** [herveaurel/HomeAssistant#4]
Bonjour, D'abord bravo pour ton super boulot. Pourrais tu partager également tes inputs? comme le input select du lave linge.
merci d'avance

**Comment by herveaurel** [comment]
Bonjour. 
Merci. 
Je vais regarder ce que je peux faire mais ils sont crées via la console et non en yaml. Et associés à une automatisation. 
Le principe pour faire simple est un input_text avec 3 choix :
- on 
- veille 
- off 

Puis une automatisation, le déclencheur est la puissance remontée par la prise connectée. 
J'ai préservé les puissances remontées dans le cas où la machine à laver était éteinte, allumée sans tourner (veille) et en cours de lavage. 
Puis dans l'auto, en déclencheurs : des seuils de valeurs. Et en action, la valeur de l'input_text que je souhaite. (Off, veille, on)
