### ISSUE TITLE
UI ou YAML ?

### ISSUE THREAD

**Issue by fifou5555** [herveaurel/HomeAssistant#5]
Salut,

Deja merci de partager ton travail c'est vraiment cool. 

J'ai une question, tu ecris dans la description que tu travail en mode UI mais je vois un dashboard entierement en YAML a coté (lovelace.yaml). 

Comment doit on utiliser ca ? 

Merci pour ta reponse !

**Comment by herveaurel** [comment]
Cela correspond à ce que tu retrouves en mode édition : 3 points en haut à droite / modifier le tableau de bord / 3 points / éditeur de configuration

**Comment by fifou5555** [comment]
Merci beaucoup ! Je ne connaissais pas du tout cette facon de faire :)

**Comment by herveaurel** [comment]
A mes débuts, je ne connaissais pas les deux méthodes. 
J'ai fait l'installation "standard". 
Ce fichier "lovelace", n'est jamais utilisé pour les créations / modifications de cartes, seulement pour y rédiger la première partie : les templates button-card. Sinon le reste c'est un gros, les onlglets et cartes réalisés via la console. 
C'est simplement le seul moyen de transmettre mon dashboard UI.
