### ISSUE TITLE
Police d'ecriture / Font

### ISSUE THREAD

**Issue by fifou5555** [herveaurel/HomeAssistant#6]
Bonjour,

J'ai remarqué que dans le theme MAD DAY il y avait une police d'ecriture "avenir". J'ai cherché comment rajouter des polices mais j'ai uniquement trouvé des techniques avec GoogleFont. Malheuresement "avenir" n'existe pas chez eux. 

Comment as-tu rajouté la police ?

Merci !

**Comment by herveaurel** [comment]
J'ai regardé dans mon Mac, logiciel Pages (équivalent Word sous Windows), les polices et leurs noms puis je les ai testé une à une. 
Je passe en force la police dans les template button card car le réglage dans le thème ne fonctionne pas correctement. 
<img width="356" alt="image" src="https://user-images.githubusercontent.com/64784541/199624039-02875061-eae3-4105-8b21-8f9f1f665b87.png">
