### ISSUE TITLE
Pourring

### ISSUE THREAD

**Issue by multinet33** [herveaurel/HomeAssistant#7]
Bonjour 

Dans le fichier sensor.yaml ligne 306 il faut enlever un r a pourring 

Et il manque le fichier pouring.svg dans le dossier icônes animes

**Comment by herveaurel** [comment]
Merci de ton retour 👍🏼
Je regarde ça dès que je peux.

**Comment by herveaurel** [comment]
> Bonjour
> 
> Dans le fichier sensor.yaml ligne 306 il faut enlever un r a pourring
> 
> Et il manque le fichier pouring.svg dans le dossier icônes animes

Faute corrigée. 
Pour l'état "pouring" j'utilise le umbrella.svg, corrigé également.
