### ISSUE TITLE
Carte personnes et activité

### ISSUE THREAD

**Issue by Milou020789** [herveaurel/HomeAssistant#8]
Bonjour Aurél, 

Tu as fait un bon travail ici, je suis fan. J'aimerais savoir comment faire pour avoir les meme carte personnes ainsi que celle d'activité?

Bàt
Milou

**Comment by herveaurel** [comment]
Bonjour, et merci. 

Ce n'est pas vraiment le lieu pour parler de ça, ce menu est fait pour les erreurs éventuellement ou les bugs. 

Il faut lire la partie Installation, car sans comprendre les templates button card, ça ne va pas être évident à mettre en place. 

Tout est sur mon github, l'aide personnalisée est réservée aux membres VIP.

**Comment by Milou020789** [comment]
Merci  pour ta reponse, peut tu juste me dire quelle yaml j'ai besoin pour les cartes?? je me debrouillerais

**Comment by herveaurel** [comment]
> Merci  pour ta reponse, peut tu juste me dire quelle yaml j'ai besoin pour les cartes?? je me debrouillerais 

Entièrement faite en template button card. 
Cherche celui nommé carte_personne_aurel
